return {
  -- {
  --   'elixir-tools/elixir-tools.nvim',
  --   version = '*',
  --   event = { 'BufReadPre', 'BufNewFile' },
  --   dependencies = { 'nvim-lua/plenary.nvim' },
  --   config = function()
  --     require('elixir').setup {
  --       nextls = {
  --         enable = false,
  --         init_options = {
  --           extensions = {
  --             credo = {
  --               enable = true,
  --               cli_options = { 'strict' },
  --             },
  --           },
  --           experimental = {
  --             completions = { enable = true },
  --           },
  --         },
  --       },
  --       elixirls = { enable = false },
  --       projectionist = { enable = true },
  --     }
  --   end,
  -- },
}
