return {
  -- { -- Autocompletion
  --   'hrsh7th/nvim-cmp',
  --   event = 'InsertEnter',
  --   dependencies = {
  --     -- Snippet Engine & its associated nvim-cmp source
  --     {
  --       'L3MON4D3/LuaSnip',
  --       build = (function()
  --         if vim.fn.has 'win32' == 1 or vim.fn.executable 'make' == 0 then
  --           return
  --         end
  --         return 'make install_jsregexp'
  --       end)(),
  --       dependencies = {
  --         -- `friendly-snippets` contains a variety of premade snippets.
  --         --    https://github.com/rafamadriz/friendly-snippets
  --         -- {
  --         --   'rafamadriz/friendly-snippets',
  --         --   config = function()
  --         --     require('luasnip.loaders.from_vscode').lazy_load()
  --         --   end,
  --         -- },
  --       },
  --     },
  --     'saadparwaiz1/cmp_luasnip',
  --     'hrsh7th/cmp-nvim-lsp',
  --     'hrsh7th/cmp-path',
  --   },
  --   opts = function(_, opts)
  --     opts.sources = opts.sources or {}
  --     table.insert(opts.sources, {
  --       name = 'lazydev',
  --       group_index = 0, -- set group index to 0 to skip loading LuaLS completions
  --     })
  --   end,
  --   config = function()
  --     -- See `:help cmp`
  --     local cmp = require 'cmp'
  --     local luasnip = require 'luasnip'
  --     luasnip.config.setup {}
  --
  --     cmp.setup {
  --       formatting = {
  --         format = function(entry, vim_item)
  --           local kind_icons = {
  --             Text = '',
  --             Color = '',
  --             Method = '',
  --             Function = '󰊕',
  --             Constructor = '',
  --             Field = '',
  --             Variable = '',
  --             Class = '',
  --             Interface = '',
  --             Module = '',
  --             Property = '',
  --             Unit = '',
  --             Value = '',
  --             Enum = '',
  --             Keyword = '',
  --             Snippet = '󰩫',
  --             File = '',
  --             Reference = '',
  --             Folder = '',
  --             EnumMember = '',
  --             Constant = '',
  --             Struct = '',
  --             Event = '',
  --             Operator = '',
  --             TypeParameter = '',
  --             Macro = '󰡱',
  --           }
  --
  --           vim_item.kind = kind_icons[vim_item.kind]
  --
  --           vim_item.menu = ({
  --             buffer = ' (Buffer)',
  --             nvim_lsp = ' (LSP)',
  --             luasnip = ' (LuaSnip)',
  --             nvim_lua = ' (Lua)',
  --             latex_symbols = ' (LaTeX)',
  --           })[entry.source.name]
  --
  --           require('tailwindcss-colorizer-cmp').formatter(entry, vim_item)
  --
  --           return vim_item
  --         end,
  --       },
  --       snippet = {
  --         expand = function(args)
  --           luasnip.lsp_expand(args.body)
  --         end,
  --       },
  --       completion = { completeopt = 'menu,menuone,noinsert' },
  --
  --       mapping = cmp.mapping.preset.insert {
  --         -- Select the [n]ext item
  --         ['<C-n>'] = cmp.mapping.select_next_item(),
  --         -- Select the [p]revious item
  --         ['<C-p>'] = cmp.mapping.select_prev_item(),
  --
  --         -- Scroll the documentation window [b]ack / [f]orward
  --         ['<C-b>'] = cmp.mapping.scroll_docs(-4),
  --         ['<C-f>'] = cmp.mapping.scroll_docs(4),
  --
  --         -- Accept ([y]es) the completion.
  --         --  This will auto-import if your LSP supports it.
  --         --  This will expand snippets if the LSP sent a snippet.
  --         ['<C-y>'] = cmp.mapping.confirm { select = true },
  --
  --         --['<CR>'] = cmp.mapping.confirm { select = true },
  --         --['<Tab>'] = cmp.mapping.select_next_item(),
  --         --['<S-Tab>'] = cmp.mapping.select_prev_item(),
  --
  --         -- Manually trigger a completion from nvim-cmp.
  --         ['<C-Space>'] = cmp.mapping.complete {},
  --
  --         -- <c-l> will move you to the right of each of the expansion locations.
  --         -- <c-h> is similar, except moving you backwards.
  --         ['<C-l>'] = cmp.mapping(function()
  --           if luasnip.expand_or_locally_jumpable() then
  --             luasnip.expand_or_jump()
  --           end
  --         end, { 'i', 's' }),
  --         ['<C-h>'] = cmp.mapping(function()
  --           if luasnip.locally_jumpable(-1) then
  --             luasnip.jump(-1)
  --           end
  --         end, { 'i', 's' }),
  --
  --         -- For more advanced Luasnip keymaps (e.g. selecting choice nodes, expansion) see:
  --         --    https://github.com/L3MON4D3/LuaSnip?tab=readme-ov-file#keymaps
  --       },
  --       sources = {
  --         { name = 'lazydev', group_index = 0 },
  --         { name = 'nvim_lsp' },
  --         { name = 'luasnip' },
  --         { name = 'path' },
  --       },
  --     }
  --   end,
  -- },
  {
    'kosayoda/nvim-lightbulb',
    config = function()
      require('nvim-lightbulb').setup {
        sign = { enabled = false },
        virtual_text = { enabled = true },
        float = { enabled = false },
        autocmd = { enabled = true },
      }
    end,
  },
  -- { -- LSP Configuration & Plugins
  --   'neovim/nvim-lspconfig',
  --   dependencies = {
  --     { 'mason-org/mason.nvim', opts = {} },
  --     'mason-org/mason-lspconfig.nvim',
  --     'WhoIsSethDaniel/mason-tool-installer.nvim',
  --     { 'j-hui/fidget.nvim',    opts = {} },
  --     'hrsh7th/cmp-nvim-lsp',
  --   },
  --   config = function()
  --     -- vim.api.nvim_create_autocmd('LspAttach', {
  --     --   group = vim.api.nvim_create_augroup('kickstart-lsp-attach', { clear = true }),
  --     --   callback = function(event)
  --     --     local map = function(keys, func, desc, mode)
  --     --       mode = mode or 'n'
  --     --       vim.keymap.set(mode, keys, func, { buffer = event.buf, desc = 'LSP: ' .. desc })
  --     --     end
  --     --
  --     --     map('grn', vim.lsp.buf.rename, '[R]e[n]ame.')
  --     --     map('gra', vim.lsp.buf.code_action, '[G]oto Code [A]ction.', { 'n', 'x' })
  --     --     map('grr', require('telescope.builtin').lsp_references, '[G]oto [R]eferences.')
  --     --     map('gri', require('telescope.builtin').lsp_implementations, '[G]oto [I]mplementations.')
  --     --     map('grd', require('telescope.builtin').lsp_definitions, '[G]oto [D]efinitions.')
  --     --     map('grD', vim.lsp.buf.declaration, '[G]oto [D]eclarations.')
  --     --     map('grt', require('telescope.builtin').lsp_type_definitions, '[G]oto [T]ype Definitions.')
  --     --
  --     --     -- Opens a popup that displays documentation about the word under your cursor
  --     --     --  See `:help K` for why this keymap.
  --     --     map('<C-q>', vim.lsp.buf.hover, 'Hover Documentation')
  --     --
  --     --     local client = vim.lsp.get_client_by_id(event.data.client_id)
  --     --     if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_documentHighlight, event.buf) then
  --     --       local highlight_augroup = vim.api.nvim_create_augroup('kickstart-lsp-highlight', { clear = false })
  --     --       vim.api.nvim_create_autocmd({ 'CursorHold', 'CursorHoldI' }, {
  --     --         buffer = event.buf,
  --     --         group = highlight_augroup,
  --     --         callback = vim.lsp.buf.document_highlight,
  --     --       })
  --     --
  --     --       vim.api.nvim_create_autocmd({ 'CursorMoved', 'CursorMovedI' }, {
  --     --         buffer = event.buf,
  --     --         group = highlight_augroup,
  --     --         callback = vim.lsp.buf.clear_references,
  --     --       })
  --     --
  --     --       vim.api.nvim_create_autocmd('LspDetach', {
  --     --         group = vim.api.nvim_create_augroup('kickstart-lsp-detach', { clear = true }),
  --     --         callback = function(event2)
  --     --           vim.lsp.buf.clear_references()
  --     --           vim.api.nvim_clear_autocmds { group = 'kickstart-lsp-highlight', buffer = event2.buf }
  --     --         end,
  --     --       })
  --     --     end
  --     --
  --     --     -- The following auto command is used to enable inlay hints in your
  --     --     -- code, if the language server you are using supports them
  --     --     --
  --     --     -- This may be unwanted, since they displace some of your code
  --     --     if client and client:supports_method(vim.lsp.protocol.Methods.textDocument_inlayHint, event.buf) then
  --     --       map('<leader>th', function()
  --     --         vim.lsp.inlay_hint.enable(not vim.lsp.inlay_hint.is_enabled { bufnr = event.buf })
  --     --       end, '[T]oggle Inlay [H]ints')
  --     --     end
  --     --   end,
  --     -- })
  --
  --     -- -- Change diagnostic symbols in the sign column (gutter)
  --     -- if vim.g.have_nerd_font then
  --     --   local signs = { ERROR = '', WARN = '', INFO = '', HINT = '' }
  --     --   local diagnostic_signs = {}
  --     --   for type, icon in pairs(signs) do
  --     --     diagnostic_signs[vim.diagnostic.severity[type]] = icon
  --     --   end
  --     --   vim.diagnostic.config { signs = { text = diagnostic_signs } }
  --     -- end
  --
  --     -- LSP servers and clients are able to communicate to each other what features they support.
  --     --  By default, Neovim doesn't support everything that is in the LSP specification.
  --     --  When you add nvim-cmp, luasnip, etc. Neovim now has *more* capabilities.
  --     --  So, we create new capabilities with nvim cmp, and then broadcast that to the servers.
  --     local capabilities = vim.lsp.protocol.make_client_capabilities()
  --     capabilities = vim.tbl_deep_extend('force', capabilities, require('cmp_nvim_lsp').default_capabilities())
  --
  --     -- Enable the following language servers
  --     --  Feel free to add/remove any LSPs that you want here. They will automatically be installed.
  --     --
  --     --  Add any additional override configuration in the following tables. Available keys are:
  --     --  - cmd (table): Override the default command used to start the server
  --     --  - filetypes (table): Override the default list of associated filetypes for the server
  --     --  - capabilities (table): Override fields in capabilities. Can be used to disable certain LSP features.
  --     --  - settings (table): Override the default settings passed when initializing the server.
  --     --        For example, to see the options for `lua_ls`, you could go to: https://luals.github.io/wiki/settings/
  --     --
  --     --  TODO: Fix in order to upgrade mason version
  --     local servers = {
  --       elixirls = {
  --         cmd = { '/home/acherry/.local/share/nvim/mason/packages/elixir-ls/language_server.sh' },
  --         settings = {
  --           elixirLs = { dializerEnabled = true },
  --         },
  --       },
  --       -- expert = {},
  --       tailwindcss = {
  --         settings = {
  --           tailwindCSS = {
  --             experimental = {
  --               configFile = 'assets/css/app.css',
  --             },
  --             includeLanguages = {
  --               elixir = 'phoenix-heex',
  --               eelixir = 'phoenix-heex',
  --               heex = 'phoenix-heex',
  --             },
  --           },
  --         },
  --         init_options = {
  --           userLanguages = {
  --             elixir = 'phoenix-heex',
  --             eelixir = 'phoenix-heex',
  --             heex = 'phoenix-heex',
  --           },
  --         },
  --         root_dir = function(fname)
  --           print("Hello World")
  --           local root_pattern = require('lspconfig').util.root_pattern
  --
  --           local root = root_pattern(
  --             'tailwind.config.mjs',
  --             'tailwind.config.cjs',
  --             'tailwind.config.js',
  --             'tailwind.config.ts',
  --             'postcss.config.js',
  --             'config/tailwind.config.js',
  --             'assets/tailwind.config.js',
  --             'assets/css/app.css'
  --           )(fname)
  --           print("FooBar")
  --           return root
  --         end,
  --       },
  --       -- lexical = {},
  --       cssls = {},
  --       -- sqlls = {},
  --       postgres_lsp = {},
  --       lua_ls = {
  --         settings = {
  --           Lua = {
  --             completion = {
  --               callSnippet = 'Replace',
  --             },
  --             diagnostics = { disable = { 'missing-fields' } },
  --           },
  --         },
  --       },
  --       clangd = {},
  --       pyright = {},
  --       ts_ls = {},
  --     }
  --
  --     -- You can add other tools here that you want Mason to install
  --     -- for you, so that they are available from within Neovim.
  --     local ensure_installed = vim.tbl_keys(servers or {})
  --     vim.list_extend(ensure_installed, {
  --       'stylua', -- Used to format Lua code
  --     })
  --     require('mason-tool-installer').setup { ensure_installed = ensure_installed }
  --
  --     require('mason-lspconfig').setup {
  --       automatic_enable = true,
  --       handlers = {
  --         function(server_name)
  --           if server_name == 'tsserver' then
  --             server_name = 'ts_ls'
  --           end
  --           local server = servers[server_name] or {}
  --           -- This handles overriding only values explicitly passed
  --           -- by the server configuration above. Useful when disabling
  --           -- certain features of an LSP (for example, turning off formatting for tsserver)
  --           server.capabilities = vim.tbl_deep_extend('force', {}, capabilities, server.capabilities or {})
  --           require('lspconfig')[server_name].setup(server)
  --         end,
  --       },
  --     }
  --   end,
  -- },
}
